"""empty message

Revision ID: 25d677da14cd
Revises: 
Create Date: 2018-04-20 09:39:01.333038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25d677da14cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sk_job_execution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('service_job_execution_id', sa.String(length=50), nullable=True),
    sa.Column('job_instance_id', sa.INTEGER(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('running_status', sa.INTEGER(), nullable=True),
    sa.Column('running_on', sa.Text(), nullable=True),
    sa.Column('export_uri', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sk_job_execution_job_instance_id'), 'sk_job_execution', ['job_instance_id'], unique=False)
    op.create_index(op.f('ix_sk_job_execution_project_id'), 'sk_job_execution', ['project_id'], unique=False)
    op.create_index(op.f('ix_sk_job_execution_service_job_execution_id'), 'sk_job_execution', ['service_job_execution_id'], unique=False)
    op.create_table('sk_job_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('spider_name', sa.String(length=100), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('spider_arguments', sa.Text(), nullable=True),
    sa.Column('priority', sa.INTEGER(), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('cron_minutes', sa.String(length=20), nullable=True),
    sa.Column('cron_hour', sa.String(length=20), nullable=True),
    sa.Column('cron_day_of_month', sa.String(length=20), nullable=True),
    sa.Column('cron_day_of_week', sa.String(length=20), nullable=True),
    sa.Column('cron_month', sa.String(length=20), nullable=True),
    sa.Column('enabled', sa.INTEGER(), nullable=True),
    sa.Column('run_type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sk_job_instance_project_id'), 'sk_job_instance', ['project_id'], unique=False)
    op.create_index(op.f('ix_sk_job_instance_spider_name'), 'sk_job_instance', ['spider_name'], unique=False)
    op.create_table('sk_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('project_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sk_spider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('spider_name', sa.String(length=100), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sk_spider_project_id'), 'sk_spider', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sk_spider_project_id'), table_name='sk_spider')
    op.drop_table('sk_spider')
    op.drop_table('sk_project')
    op.drop_index(op.f('ix_sk_job_instance_spider_name'), table_name='sk_job_instance')
    op.drop_index(op.f('ix_sk_job_instance_project_id'), table_name='sk_job_instance')
    op.drop_table('sk_job_instance')
    op.drop_index(op.f('ix_sk_job_execution_service_job_execution_id'), table_name='sk_job_execution')
    op.drop_index(op.f('ix_sk_job_execution_project_id'), table_name='sk_job_execution')
    op.drop_index(op.f('ix_sk_job_execution_job_instance_id'), table_name='sk_job_execution')
    op.drop_table('sk_job_execution')
    # ### end Alembic commands ###
